// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrUxBd9ev0iSmvw8cDXQWzATrq5V5uslY',
    appId: '1:330210976660:web:6951c14a48ed6cb8732581',
    messagingSenderId: '330210976660',
    projectId: 'union-shop-bdb40',
    authDomain: 'union-shop-bdb40.firebaseapp.com',
    databaseURL: 'https://union-shop-bdb40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'union-shop-bdb40.firebasestorage.app',
    measurementId: 'G-GXCDJNBS7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiZknqOqjMcwuboPLe5FK3vg6a2TPKRcY',
    appId: '1:330210976660:android:04fa46446e407d7d732581',
    messagingSenderId: '330210976660',
    projectId: 'union-shop-bdb40',
    databaseURL: 'https://union-shop-bdb40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'union-shop-bdb40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivN1UpaMWTx0u_ySey1bfSMlvgD_FWWM',
    appId: '1:330210976660:ios:46727b8e0394210b732581',
    messagingSenderId: '330210976660',
    projectId: 'union-shop-bdb40',
    databaseURL: 'https://union-shop-bdb40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'union-shop-bdb40.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivN1UpaMWTx0u_ySey1bfSMlvgD_FWWM',
    appId: '1:330210976660:ios:46727b8e0394210b732581',
    messagingSenderId: '330210976660',
    projectId: 'union-shop-bdb40',
    databaseURL: 'https://union-shop-bdb40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'union-shop-bdb40.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrUxBd9ev0iSmvw8cDXQWzATrq5V5uslY',
    appId: '1:330210976660:web:f35a5e003169e19b732581',
    messagingSenderId: '330210976660',
    projectId: 'union-shop-bdb40',
    authDomain: 'union-shop-bdb40.firebaseapp.com',
    databaseURL: 'https://union-shop-bdb40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'union-shop-bdb40.firebasestorage.app',
    measurementId: 'G-V047E1PHJQ',
  );
}
